/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Default = number | boolean | string;
export type Label = string;
export type AxisType = "mouse.x" | "mouse.y" | "mouse.wheel";
export type CurveType = "linear" | "exponential" | "sine" | "discrete";
export type Scale = number;
export type Sensitivity = number;
export type Keys = string[] | null;
export type Mousebuttons = string[] | null;
export type Strict = boolean;
export type Wheel = boolean | null;
export type Mappings = Mapping[];
export type Max = number | null;
export type Min = number | null;
export type Options = string[] | null;
export type Parameter = string;
export type Smoothingtime = number;
export type Step = number | null;
export type DataType = "float" | "int" | "bool" | "string";
export type Unit = string;

export interface Control {
  default: Default;
  label: Label;
  mappings: Mappings;
  max?: Max;
  min?: Min;
  options?: Options;
  parameter: Parameter;
  smoothingTime?: Smoothingtime;
  step?: Step;
  type: DataType;
  unit: Unit;
}
export interface Mapping {
  action: ActionType;
  combo: ComboType;
  [k: string]: unknown;
}
export interface ActionType {
  axis: AxisType;
  curve?: CurveType;
  scale?: Scale;
  sensitivity: Sensitivity;
  [k: string]: unknown;
}
export interface ComboType {
  keys?: Keys;
  mouseButtons?: Mousebuttons;
  strict?: Strict;
  wheel?: Wheel;
  [k: string]: unknown;
}
