/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Description of the haptic configuration
 */
export type Description = string | null;
/**
 * Unit of measurement for the option
 */
export type Unit = string;
/**
 * Value of the device option
 */
export type Value = number;
/**
 * Type of haptic device
 */
export type Type = string;
export type HapticId = number;
/**
 * Maximum allowed value
 */
export type Max = number | null;
/**
 * Minimum allowed value
 */
export type Min = number | null;
/**
 * Name of the parameter
 */
export type Name = string;
/**
 * Available options for enum types
 */
export type Options1 = string[] | null;
/**
 * The parameter
 */
export type Parameter = string;
/**
 * Path to the parameter
 */
export type Path = string;
/**
 * Smoothing time in seconds
 */
export type Smoothingtime = number | null;
/**
 * Step increment value
 */
export type Step = number | null;
/**
 * Data type of the parameter
 */
export type Type1 = string;
/**
 * Unit of measurement
 */
export type Unit1 = string;
/**
 * List of input parameters
 */
export type InputParameters = HapticParameter[];
/**
 * Metadata about the haptic configuration
 */
export type MetaInfo = {
  [k: string]: unknown;
} | null;
/**
 * Name of the haptic configuration
 */
export type Name1 = string;

export interface Haptic {
  description?: Description;
  device: DeviceConfig;
  haptic_id: HapticId;
  input_parameters: InputParameters;
  meta_info?: MetaInfo;
  name: Name1;
  [k: string]: unknown;
}
/**
 * Device configuration
 */
export interface DeviceConfig {
  options: Options;
  type: Type;
  [k: string]: unknown;
}
/**
 * Device-specific configuration options
 */
export interface Options {
  [k: string]: DeviceOptionValue;
}
export interface DeviceOptionValue {
  unit: Unit;
  value: Value;
  [k: string]: unknown;
}
export interface HapticParameter {
  default: Default;
  max?: Max;
  min?: Min;
  name: Name;
  options?: Options1;
  parameter: Parameter;
  path: Path;
  smoothingTime?: Smoothingtime;
  step?: Step;
  type: Type1;
  unit: Unit1;
  [k: string]: unknown;
}
/**
 * Default value
 */
export interface Default {
  [k: string]: unknown;
}
