/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Effects applied when the rule is triggered
 */
export type Effects =
  | {
      [k: string]: unknown;
    }[]
  | null;
/**
 * Execution environment for the rule
 */
export type Execution = string | null;
/**
 * Expression defining the rule logic
 */
export type Expr =
  | string
  | {
      [k: string]: unknown;
    }
  | null;
/**
 * Unique rule identifier
 */
export type Id = string;
/**
 * Parameter path the rule targets
 */
export type Target = string | null;
/**
 * Trigger configuration for the rule
 */
export type Trigger = {
  [k: string]: unknown;
} | null;

export interface Rule {
  effects?: Effects;
  execution?: Execution;
  expr?: Expr;
  id: Id;
  target?: Target;
  trigger?: Trigger;
}
