/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Creation time
 */
export type CreatedAt = string | null;
/**
 * Bundle details
 */
export type Description = string | null;
/**
 * Database ID
 */
export type Id = number | null;
/**
 * Human readable bundle name
 */
export type Name = string;
/**
 * Effects applied when the rule is triggered
 */
export type Effects =
  | {
      [k: string]: unknown;
    }[]
  | null;
/**
 * Execution environment for the rule
 */
export type Execution = string | null;
/**
 * Expression defining the rule logic
 */
export type Expr =
  | string
  | {
      [k: string]: unknown;
    }
  | null;
/**
 * Unique rule identifier
 */
export type Id1 = string;
/**
 * Parameter path the rule targets
 */
export type Target = string | null;
/**
 * Trigger configuration for the rule
 */
export type Trigger = {
  [k: string]: unknown;
} | null;
/**
 * List of rules
 */
export type Rules = Rule[];
/**
 * Last update time
 */
export type UpdatedAt = string | null;

export interface RuleBundle {
  created_at?: CreatedAt;
  description?: Description;
  id?: Id;
  meta_info?: MetaInfo;
  name: Name;
  rules: Rules;
  updated_at?: UpdatedAt;
}
/**
 * Metadata about the rule bundle
 */
export interface MetaInfo {
  [k: string]: unknown;
}
/**
 * Representation of a single rule within a bundle.
 */
export interface Rule {
  effects?: Effects;
  execution?: Execution;
  expr?: Expr;
  id: Id1;
  target?: Target;
  trigger?: Trigger;
}
