/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Description = string | null;
/**
 * GLSL fragment shader code
 */
export type FragmentShader = string;
export type InputParameters = InputParameter[] | null;
export type Default = number;
export type Max = number;
export type Min = number;
export type Name = string;
export type Parameter = string;
export type Path = string;
export type Smoothingtime = number | null;
export type Step = number | null;
export type Type = string;
/**
 * Metadata about the shader
 */
export type MetaInfo = {
  [k: string]: unknown;
} | null;
/**
 * Name of the shader
 */
export type Name1 = string;
export type Uniforms = UniformDef[] | null;
export type Name2 = string;
export type Stage = string;
export type Type1 = string;
/**
 * GLSL vertex shader code
 */
export type VertexShader = string;

export interface Shader {
  description?: Description;
  fragment_shader: FragmentShader;
  input_parameters?: InputParameters;
  meta_info?: MetaInfo;
  name: Name1;
  uniforms?: Uniforms;
  vertex_shader: VertexShader;
}
export interface InputParameter {
  default: Default;
  max: Max;
  min: Min;
  name: Name;
  parameter: Parameter;
  path: Path;
  smoothingTime?: Smoothingtime;
  step?: Step;
  type: Type;
  [k: string]: unknown;
}
export interface UniformDef {
  default: Default1;
  name: Name2;
  stage: Stage;
  type: Type1;
  [k: string]: unknown;
}
export interface Default1 {
  [k: string]: unknown;
}
