# generated by datamodel-codegen:
#   filename:  synesthetic-asset.schema.json
#   timestamp: 2025-08-27T19:29:37+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Optional

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, constr


class ScaleProfile(Enum):
    linear = 'linear'
    exponential = 'exponential'
    logarithmic = 'logarithmic'
    sine = 'sine'
    cosine = 'cosine'


class Type(Enum):
    additive = 'additive'
    multiplicative = 'multiplicative'


class Waveform(Enum):
    sine = 'sine'
    triangle = 'triangle'
    square = 'square'
    sawtooth = 'sawtooth'


class ModulationItem(BaseModel):
    amplitude: float = Field(
        ..., description='Amplitude of the modulation', title='Amplitude'
    )
    frequency: float = Field(
        ..., description='Frequency of the modulation in Hz', title='Frequency'
    )
    id: str = Field(..., description='Unique identifier for the modulation', title='Id')
    max: Optional[float] = Field(
        None, description='Maximum allowable value for the modulation', title='Max'
    )
    min: Optional[float] = Field(
        None, description='Minimum allowable value for the modulation', title='Min'
    )
    offset: float = Field(
        ..., description='Offset/base value of the modulation', title='Offset'
    )
    phase: float = Field(..., description='Phase offset in radians', title='Phase')
    scale: Optional[float] = Field(
        1.0,
        description='Scaling factor applied to the modulation output',
        title='Scale',
    )
    scaleProfile: Optional[ScaleProfile] = Field(
        None,
        description='Response profile to shape the modulation output',
        title='Scaleprofile',
    )
    target: str = Field(
        ...,
        description="Target parameter path (e.g., 'visual.u_wave_speed', 'tone.filter.frequency')",
        title='Target',
    )
    type: Type = Field(..., description='Type of modulation', title='Type')
    waveform: Waveform = Field(..., description='Waveform type', title='Waveform')


class NestedControlResponse(BaseModel):
    control_parameters: Optional[list[dict[str, Any]]] = Field(
        None, title='Control Parameters'
    )
    description: Optional[str] = Field(None, title='Description')
    meta_info: Optional[dict[str, Any]] = Field(None, title='Meta Info')
    name: str = Field(..., title='Name')


class NestedHapticResponse(BaseModel):
    description: Optional[str] = Field(None, title='Description')
    device: Optional[dict[str, Any]] = Field(None, title='Device')
    input_parameters: Optional[list[dict[str, Any]]] = Field(
        None, title='Input Parameters'
    )
    meta_info: Optional[dict[str, Any]] = Field(None, title='Meta Info')
    name: str = Field(..., title='Name')


class NestedShaderResponse(BaseModel):
    description: Optional[str] = Field(None, title='Description')
    fragment_shader: str = Field(..., title='Fragment Shader')
    input_parameters: Optional[list[dict[str, Any]]] = Field(
        None, title='Input Parameters'
    )
    meta_info: Optional[dict[str, Any]] = Field(None, title='Meta Info')
    name: str = Field(..., title='Name')
    shader_lib_id: Optional[int] = Field(None, title='Shader Lib Id')
    uniforms: Optional[list[dict[str, Any]]] = Field([], title='Uniforms')
    vertex_shader: str = Field(..., title='Vertex Shader')


class NestedToneResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    description: Optional[str] = Field(None, title='Description')
    effects: Optional[list[dict[str, Any]]] = Field(None, title='Effects')
    input_parameters: Optional[list[dict[str, Any]]] = Field(
        None, title='Input Parameters'
    )
    meta_info: Optional[dict[str, Any]] = Field(None, title='Meta Info')
    name: str = Field(..., title='Name')
    parts: Optional[list[dict[str, Any]]] = Field(None, title='Parts')
    patterns: Optional[list[dict[str, Any]]] = Field(None, title='Patterns')
    synth: dict[str, Any] = Field(..., title='Synth')


class Modulation(BaseModel):
    description: Optional[str] = Field(
        None, description='Description of the modulation set', title='Description'
    )
    meta_info: Optional[dict[str, Any]] = Field(
        None,
        description='Metadata about the modulation set',
        examples=[
            {
                'category': 'modulation',
                'complexity': 'medium',
                'tags': ['multimodal', 'dynamic'],
            }
        ],
        title='Meta Info',
    )
    modulation_id: int = Field(..., title='Modulation Id')
    modulations: list[ModulationItem] = Field(
        ...,
        description='List of modulations',
        examples=[
            {
                'amplitude': 0.5,
                'frequency': 0.5,
                'id': 'wave_speed_pulse',
                'max': 1.0,
                'min': 0.0,
                'offset': 1.0,
                'phase': 0.0,
                'scale': 1.0,
                'scaleProfile': 'linear',
                'target': 'visual.u_wave_speed',
                'type': 'additive',
                'waveform': 'triangle',
            },
            {
                'amplitude': 400,
                'frequency': 0.25,
                'id': 'filter_sweep',
                'max': 1.0,
                'min': 0.0,
                'offset': 800,
                'phase': 0.0,
                'scale': 1.0,
                'scaleProfile': 'exponential',
                'target': 'tone.filter.frequency',
                'type': 'additive',
                'waveform': 'triangle',
            },
            {
                'amplitude': 0.2,
                'frequency': 1.0,
                'id': 'haptic_pulse',
                'max': 1.0,
                'min': 0.0,
                'offset': 0.6,
                'phase': 0.0,
                'scale': 1.0,
                'scaleProfile': 'linear',
                'target': 'haptic.intensity',
                'type': 'additive',
                'waveform': 'sine',
            },
        ],
        title='Modulations',
    )
    name: str = Field(..., description='Name of the modulation set', title='Name')


class SynestheticAsset(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    control: Optional[NestedControlResponse] = None
    control_id: Optional[int] = Field(None, title='Control Id')
    control_parameters: Optional[list[dict[str, Any]]] = Field(
        None, title='Control Parameters'
    )
    created_at: AwareDatetime = Field(..., title='Created At')
    description: Optional[str] = Field(
        None,
        description="Description of the asset's purpose",
        examples=[
            'A circle that pulses and changes color and sound frequency based on user controls'
        ],
        title='Description',
    )
    haptic: Optional[NestedHapticResponse] = None
    haptic_id: Optional[int] = Field(None, title='Haptic Id')
    meta_info: Optional[dict[str, Any]] = Field(
        None,
        description='Metadata about the asset',
        examples=[
            {
                'category': 'visual',
                'complexity': 'medium',
                'tags': ['geometric', 'reactive', 'audio'],
            }
        ],
        title='Meta Info',
    )
    modulation: Optional[Modulation] = None
    modulation_id: Optional[int] = Field(None, title='Modulation Id')
    modulations: Optional[list[dict[str, Any]]] = Field(
        None,
        description='Array of modulations for this asset',
        examples=[
            {
                'amplitude': 0.5,
                'frequency': 0.5,
                'id': 'wave_speed_pulse',
                'max': 1.0,
                'min': 0.0,
                'offset': 1.0,
                'phase': 0.0,
                'scale': 1.0,
                'scaleProfile': 'linear',
                'target': 'visual.u_wave_speed',
                'type': 'additive',
                'waveform': 'triangle',
            }
        ],
        title='Modulations',
    )
    name: constr(min_length=1) = Field(
        ...,
        description='Name of the synesthetic asset',
        examples=['Circle Pulsar'],
        title='Name',
    )
    rule_bundle_id: Optional[int] = Field(None, title='Rule Bundle Id')
    shader: Optional[NestedShaderResponse] = None
    shader_id: Optional[int] = Field(None, title='Shader Id')
    synesthetic_asset_id: int = Field(..., title='Synesthetic Asset Id')
    tone: Optional[NestedToneResponse] = None
    tone_id: Optional[int] = Field(None, title='Tone Id')
    updated_at: AwareDatetime = Field(..., title='Updated At')
