# generated by datamodel-codegen:
#   filename:  control-bundle.schema.json

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel, Extra, Field

from . import control_schema


class ControlBundle(BaseModel):
    class Config:
        extra = Extra.forbid

    control_parameters: List[control_schema.Control] = Field(
        ..., title='Control Parameters'
    )
    description: str | None = Field(None, title='Description')
    meta_info: Dict[str, Any] | None = Field(None, title='Meta Info')
    name: str = Field(..., title='Name')
