# generated by datamodel-codegen:
#   filename:  control.schema.json

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, Extra, Field


class AxisType(Enum):
    mouse_x = 'mouse.x'
    mouse_y = 'mouse.y'
    mouse_wheel = 'mouse.wheel'


class ComboType(BaseModel):
    keys: List[str] | None = Field(None, title='Keys')
    mouseButtons: List[str] | None = Field(None, title='Mousebuttons')
    strict: bool | None = Field(False, title='Strict')
    wheel: bool | None = Field(None, title='Wheel')


class CurveType(Enum):
    linear = 'linear'
    exponential = 'exponential'
    sine = 'sine'
    discrete = 'discrete'


class DataType(Enum):
    float = 'float'
    int = 'int'
    bool = 'bool'
    string = 'string'


class ActionType(BaseModel):
    axis: AxisType
    curve: CurveType | None = None
    scale: float | None = Field(1.0, title='Scale')
    sensitivity: float = Field(..., title='Sensitivity')


class Mapping(BaseModel):
    action: ActionType
    combo: ComboType


class Control(BaseModel):
    class Config:
        extra = Extra.forbid

    default: float | int | bool | str = Field(..., title='Default')
    label: str = Field(..., min_length=1, title='Label')
    mappings: List[Mapping] = Field(..., title='Mappings')
    max: float | None = Field(None, title='Max')
    min: float | None = Field(None, title='Min')
    options: List[str] | None = Field(None, title='Options')
    parameter: str = Field(..., min_length=1, title='Parameter')
    smoothingTime: float | None = Field(0.0, title='Smoothingtime')
    step: float | None = Field(None, title='Step')
    type: DataType
    unit: str = Field(..., min_length=1, title='Unit')
