# generated by datamodel-codegen:
#   filename:  haptic.schema.json
#   timestamp: 2025-08-27T18:58:25+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, Field


class DeviceOptionValue(BaseModel):
    unit: str = Field(
        ..., description='Unit of measurement for the option', title='Unit'
    )
    value: float = Field(..., description='Value of the device option', title='Value')


class HapticParameter(BaseModel):
    default: Any = Field(..., description='Default value', title='Default')
    max: Optional[float] = Field(None, description='Maximum allowed value', title='Max')
    min: Optional[float] = Field(None, description='Minimum allowed value', title='Min')
    name: str = Field(..., description='Name of the parameter', title='Name')
    options: Optional[list[str]] = Field(
        None, description='Available options for enum types', title='Options'
    )
    parameter: str = Field(..., description='The parameter', title='Parameter')
    path: str = Field(..., description='Path to the parameter', title='Path')
    smoothingTime: Optional[float] = Field(
        None, description='Smoothing time in seconds', title='Smoothingtime'
    )
    step: Optional[float] = Field(
        None, description='Step increment value', title='Step'
    )
    type: str = Field(..., description='Data type of the parameter', title='Type')
    unit: str = Field(..., description='Unit of measurement', title='Unit')


class DeviceConfig(BaseModel):
    options: dict[str, DeviceOptionValue] = Field(
        ..., description='Device-specific configuration options', title='Options'
    )
    type: str = Field(..., description='Type of haptic device', title='Type')


class Haptic(BaseModel):
    description: Optional[str] = Field(
        None, description='Description of the haptic configuration', title='Description'
    )
    device: DeviceConfig = Field(..., description='Device configuration')
    haptic_id: int = Field(..., title='Haptic Id')
    input_parameters: list[HapticParameter] = Field(
        ..., description='List of input parameters', title='Input Parameters'
    )
    meta_info: Optional[dict[str, Any]] = Field(
        None,
        description='Metadata about the haptic configuration',
        examples=[
            {
                'category': 'haptic',
                'complexity': 'medium',
                'tags': ['vibration', 'feedback'],
            }
        ],
        title='Meta Info',
    )
    name: str = Field(..., description='Name of the haptic configuration', title='Name')
