# generated by datamodel-codegen:
#   filename:  rule-bundle.schema.json
#   timestamp: 2025-08-27T19:29:45+00:00

from __future__ import annotations

from typing import Any, Optional, Union

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class RuleSchema(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    effects: Optional[list[dict[str, Any]]] = Field(
        None, description='Effects applied when the rule is triggered', title='Effects'
    )
    execution: Optional[str] = Field(
        None, description='Execution environment for the rule', title='Execution'
    )
    expr: Optional[Union[str, dict[str, Any]]] = Field(
        None, description='Expression defining the rule logic', title='Expr'
    )
    id: str = Field(..., description='Unique rule identifier', title='Id')
    target: Optional[str] = Field(
        None, description='Parameter path the rule targets', title='Target'
    )
    trigger: Optional[dict[str, Any]] = Field(
        None, description='Trigger configuration for the rule', title='Trigger'
    )


class RuleBundleSchema(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    created_at: Optional[AwareDatetime] = Field(
        None, description='Creation time', title='Created At'
    )
    description: Optional[str] = Field(
        None, description='Bundle details', title='Description'
    )
    id: Optional[int] = Field(None, description='Database ID', title='Id')
    meta_info: Optional[dict[str, Any]] = Field(
        None, description='Metadata about the rule bundle', title='Meta Info'
    )
    name: str = Field(..., description='Human readable bundle name', title='Name')
    rules: list[RuleSchema] = Field(..., description='List of rules', title='Rules')
    updated_at: Optional[AwareDatetime] = Field(
        None, description='Last update time', title='Updated At'
    )
