# generated by datamodel-codegen:
#   filename:  synesthetic-asset.schema.json

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List

from pydantic import BaseModel, Extra, Field

from . import rule_bundle_schema


class ScaleProfile(Enum):
    linear = 'linear'
    exponential = 'exponential'
    logarithmic = 'logarithmic'
    sine = 'sine'
    cosine = 'cosine'


class Type(Enum):
    additive = 'additive'
    multiplicative = 'multiplicative'


class Waveform(Enum):
    sine = 'sine'
    triangle = 'triangle'
    square = 'square'
    sawtooth = 'sawtooth'


class ModulationItem(BaseModel):
    amplitude: float = Field(
        ..., description='Amplitude of the modulation', title='Amplitude'
    )
    frequency: float = Field(
        ..., description='Frequency of the modulation in Hz', title='Frequency'
    )
    id: str = Field(..., description='Unique identifier for the modulation', title='Id')
    max: float | None = Field(
        None, description='Maximum allowable value for the modulation', title='Max'
    )
    min: float | None = Field(
        None, description='Minimum allowable value for the modulation', title='Min'
    )
    offset: float = Field(
        ..., description='Offset/base value of the modulation', title='Offset'
    )
    phase: float = Field(..., description='Phase offset in radians', title='Phase')
    scale: float | None = Field(
        1, description='Scaling factor applied to the modulation output', title='Scale'
    )
    scaleProfile: ScaleProfile | None = Field(
        None,
        description='Response profile to shape the modulation output',
        title='Scaleprofile',
    )
    target: str = Field(
        ...,
        description="Target parameter path (e.g., 'visual.u_wave_speed', 'tone.filter.frequency')",
        title='Target',
    )
    type: Type = Field(..., description='Type of modulation', title='Type')
    waveform: Waveform = Field(..., description='Waveform type', title='Waveform')


class NestedControlResponse(BaseModel):
    control_parameters: List[Dict[str, Any]] | None = Field(
        None, title='Control Parameters'
    )
    description: str | None = Field(None, title='Description')
    meta_info: Dict[str, Any] | None = Field(None, title='Meta Info')
    name: str = Field(..., title='Name')


class NestedHapticResponse(BaseModel):
    description: str | None = Field(None, title='Description')
    device: Dict[str, Any] | None = Field(None, title='Device')
    input_parameters: List[Dict[str, Any]] | None = Field(
        None, title='Input Parameters'
    )
    meta_info: Dict[str, Any] | None = Field(None, title='Meta Info')
    name: str = Field(..., title='Name')


class NestedShaderResponse(BaseModel):
    description: str | None = Field(None, title='Description')
    fragment_shader: str = Field(..., title='Fragment Shader')
    input_parameters: List[Dict[str, Any]] | None = Field(
        None, title='Input Parameters'
    )
    meta_info: Dict[str, Any] | None = Field(None, title='Meta Info')
    name: str = Field(..., title='Name')
    shader_lib_id: int | None = Field(None, title='Shader Lib Id')
    uniforms: List[Dict[str, Any]] | None = Field([], title='Uniforms')
    vertex_shader: str = Field(..., title='Vertex Shader')


class NestedToneResponse(BaseModel):
    class Config:
        extra = Extra.allow

    description: str | None = Field(None, title='Description')
    effects: List[Dict[str, Any]] | None = Field(None, title='Effects')
    input_parameters: List[Dict[str, Any]] | None = Field(
        None, title='Input Parameters'
    )
    meta_info: Dict[str, Any] | None = Field(None, title='Meta Info')
    name: str = Field(..., title='Name')
    parts: List[Dict[str, Any]] | None = Field(None, title='Parts')
    patterns: List[Dict[str, Any]] | None = Field(None, title='Patterns')
    synth: Dict[str, Any] = Field(..., title='Synth')


class Modulation(BaseModel):
    description: str | None = Field(
        None, description='Description of the modulation set', title='Description'
    )
    meta_info: Dict[str, Any] | None = Field(
        None,
        description='Metadata about the modulation set',
        examples=[
            {
                'category': 'modulation',
                'complexity': 'medium',
                'tags': ['multimodal', 'dynamic'],
            }
        ],
        title='Meta Info',
    )
    modulation_id: int = Field(..., title='Modulation Id')
    modulations: List[ModulationItem] = Field(
        ...,
        description='List of modulations',
        examples=[
            {
                'amplitude': 0.5,
                'frequency': 0.5,
                'id': 'wave_speed_pulse',
                'max': 1,
                'min': 0,
                'offset': 1,
                'phase': 0,
                'scale': 1,
                'scaleProfile': 'linear',
                'target': 'visual.u_wave_speed',
                'type': 'additive',
                'waveform': 'triangle',
            },
            {
                'amplitude': 400,
                'frequency': 0.25,
                'id': 'filter_sweep',
                'max': 1,
                'min': 0,
                'offset': 800,
                'phase': 0,
                'scale': 1,
                'scaleProfile': 'exponential',
                'target': 'tone.filter.frequency',
                'type': 'additive',
                'waveform': 'triangle',
            },
            {
                'amplitude': 0.2,
                'frequency': 1,
                'id': 'haptic_pulse',
                'max': 1,
                'min': 0,
                'offset': 0.6,
                'phase': 0,
                'scale': 1,
                'scaleProfile': 'linear',
                'target': 'haptic.intensity',
                'type': 'additive',
                'waveform': 'sine',
            },
        ],
        title='Modulations',
    )
    name: str = Field(..., description='Name of the modulation set', title='Name')


class SynestheticAsset(BaseModel):
    class Config:
        extra = Extra.forbid

    control: NestedControlResponse | None = None
    control_parameters: List[Dict[str, Any]] | None = Field(
        None, title='Control Parameters'
    )
    created_at: datetime | None = None
    description: str | None = Field(
        None,
        description="Description of the asset's purpose",
        examples=[
            'A circle that pulses and changes color and sound frequency based on user controls'
        ],
        title='Description',
    )
    haptic: NestedHapticResponse | None = None
    meta_info: Dict[str, Any] | None = Field(
        None,
        description='Metadata about the asset',
        examples=[
            {
                'category': 'visual',
                'complexity': 'medium',
                'tags': ['geometric', 'reactive', 'audio'],
            }
        ],
        title='Meta Info',
    )
    modulation: Modulation | None = None
    modulations: List[Dict[str, Any]] | None = Field(
        None,
        description='Array of modulations for this asset',
        examples=[
            {
                'amplitude': 0.5,
                'frequency': 0.5,
                'id': 'wave_speed_pulse',
                'max': 1,
                'min': 0,
                'offset': 1,
                'phase': 0,
                'scale': 1,
                'scaleProfile': 'linear',
                'target': 'visual.u_wave_speed',
                'type': 'additive',
                'waveform': 'triangle',
            }
        ],
        title='Modulations',
    )
    name: str = Field(
        ...,
        description='Name of the synesthetic asset',
        examples=['Circle Pulsar'],
        min_length=1,
        title='Name',
    )
    rule_bundle: rule_bundle_schema.RuleBundleSchema | None = None
    shader: NestedShaderResponse | None = None
    tone: NestedToneResponse | None = None
    updated_at: datetime | None = None
