# generated by datamodel-codegen:
#   filename:  tone.schema.json
#   timestamp: 2025-08-27T17:54:23+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Optional, Union

from pydantic import BaseModel, Extra, Field


class SynthType(Enum):
    Tone_Synth = 'Tone.Synth'
    Tone_PolySynth = 'Tone.PolySynth'
    Tone_MonoSynth = 'Tone.MonoSynth'
    Tone_FMSynth = 'Tone.FMSynth'
    Tone_AMSynth = 'Tone.AMSynth'
    Tone_DuoSynth = 'Tone.DuoSynth'
    Tone_MembraneSynth = 'Tone.MembraneSynth'
    Tone_MetalSynth = 'Tone.MetalSynth'
    Tone_PluckSynth = 'Tone.PluckSynth'


class ToneEffect(BaseModel):
    class Config:
        extra = Extra.allow

    options: dict[str, Any] = Field(..., title='Options')
    order: int = Field(..., title='Order')
    type: str = Field(..., title='Type')


class ToneMetaInfo(BaseModel):
    class Config:
        extra = Extra.allow

    category: str = Field(..., title='Category')
    complexity: str = Field(..., title='Complexity')
    tags: list[str] = Field(..., title='Tags')


class ToneParameter(BaseModel):
    class Config:
        extra = Extra.allow

    default: Any = Field(..., title='Default')
    max: Any = Field(None, title='Max')
    min: Any = Field(None, title='Min')
    name: str = Field(..., title='Name')
    options: Optional[list[str]] = Field(None, title='Options')
    parameter: Optional[str] = Field(None, title='Parameter')
    path: str = Field(..., title='Path')
    smoothingTime: Optional[float] = Field(None, title='Smoothingtime')
    type: str = Field(..., title='Type')
    unit: Optional[str] = Field(None, title='Unit')


class TonePart(BaseModel):
    class Config:
        extra = Extra.allow

    duration: str = Field(..., title='Duration')
    id: str = Field(..., title='Id')
    loop: Optional[bool] = Field(None, title='Loop')
    pattern: str = Field(..., title='Pattern')
    start: str = Field(..., title='Start')


class TonePattern(BaseModel):
    class Config:
        extra = Extra.allow

    id: str = Field(..., title='Id')
    options: dict[str, Any] = Field(..., title='Options')
    type: str = Field(..., title='Type')


class ToneSynthOptions(BaseModel):
    class Config:
        extra = Extra.allow

    envelope: dict[str, Any] = Field(..., title='Envelope')
    filter: Optional[dict[str, Any]] = Field(None, title='Filter')
    filterEnvelope: Optional[dict[str, Any]] = Field(None, title='Filterenvelope')
    oscillator: dict[str, Any] = Field(..., title='Oscillator')
    portamento: Optional[Union[float, dict[str, Any]]] = Field(None, title='Portamento')
    volume: Union[float, dict[str, Any]] = Field(..., title='Volume')


class ToneSynth(BaseModel):
    class Config:
        extra = Extra.allow

    options: Union[ToneSynthOptions, dict[str, Any]] = Field(..., title='Options')
    type: SynthType


class Tone(BaseModel):
    class Config:
        extra = Extra.allow

    description: Optional[str] = Field(
        None, description='Description of the tone', title='Description'
    )
    effects: Optional[list[Union[ToneEffect, dict[str, Any]]]] = Field(
        None, description='Effects configuration', title='Effects'
    )
    input_parameters: Optional[list[Union[ToneParameter, dict[str, Any]]]] = Field(
        None, description='Tone input parameters', title='Input Parameters'
    )
    meta_info: Optional[Union[ToneMetaInfo, dict[str, Any]]] = Field(
        None, description='Additional metadata about the tone', title='Meta Info'
    )
    name: str = Field(..., description='Name of the tone', title='Name')
    parts: Optional[list[Union[TonePart, dict[str, Any]]]] = Field(
        None, description='Parts configuration', title='Parts'
    )
    patterns: Optional[list[Union[TonePattern, dict[str, Any]]]] = Field(
        None, description='Patterns configuration', title='Patterns'
    )
    synth: Union[ToneSynth, dict[str, Any]] = Field(
        ..., description='Synth configuration', title='Synth'
    )
    tone_id: int = Field(..., title='Tone Id')
