name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node deps
        run: npm ci

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip wheel poetry

      - name: Install Python deps (Poetry)
        run: |
          poetry install --with dev --no-root --no-interaction --no-ansi

      - name: Selective paths (codegen-related)
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            codegen:
              - 'jsonschema/**'
              - 'codegen/**'
              - 'scripts/**'
              - 'pyproject.toml'
              - 'poetry.lock'
              - 'package.json'
              - 'package-lock.json'
              - 'Makefile'

      - name: Run preflight (with codegen-check)
        if: steps.changes.outputs.codegen == 'true'
        run: |
          bash ./preflight.sh

      - name: Run preflight (skip codegen-check)
        if: steps.changes.outputs.codegen != 'true'
        run: |
          SKIP_CODEGEN_CHECK=1 bash ./preflight.sh
